### ISSUE TITLE
亲，能不能做成傻瓜点的，小白确实不好弄啊

### ISSUE THREAD

**Issue by cwm881012** [FenDou1204/SanJinXianFeng#1]
继续加油啊

**Comment by FenDou1204** [comment]
今晚编写一个windows下的执行教程和一个linux下执行教程，希望有所帮助^v^.

**Comment by cwm881012** [comment]
谢谢您的分享，历经千辛万苦，终于在windows下成功，大佬考不考虑做一个腾讯云函数版，这样就比较方便，嘻嘻

**Comment by FenDou1204** [comment]
目前考虑的内容有以下两点：
1. 优化代码里面的函数实现，代码规范话。
2. 最重要的是，准备使用云服务器通过微信公众号来每日定时发送当日学习积分。目前已在规划中。

**Comment by FenDou1204** [comment]
> 谢谢您的分享，历经千辛万苦，终于在windows下成功，大佬考不考虑做一个腾讯云函数版，这样就比较方便，嘻嘻

关于如何每日自动执行，linux下有工具 `crond` ，此工具可每日定时执行任务，达到自动学习目的。猜测windows下也应当有相应的定时任务工具，可以搜索使用。
