### ISSUE TITLE
大神求助。运行出错

### ISSUE THREAD

**Issue by sanjinxianfeng** [FenDou1204/SanJinXianFeng#5]
C:\Users\Administrator\Desktop\SanJinXianFeng-main>python sjxf_main.py

    =============================
    * 伟大的中国人民万岁        *
    * 伟大的中国共产党万岁      *
    * 伟大的毛主席万岁          *
    * 伟大的小平同志万岁        *
    =============================

    =============================
    *       三晋先锋助手        *
    =============================

Traceback (most recent call last):
  File "sjxf_main.py", line 31, in <module>
    sanjin = SanJinXianFengData(login_msg.LoginName(), login_msg.LoginPasswordEn
crypt())
  File "C:\Users\Administrator\Desktop\SanJinXianFeng-main\sjxf_user.py", line 5
6, in LoginName
    return self.__login_name
AttributeError: 'SanJinXianFengLoginInfo' object has no attribute '_SanJinXianFe
ngLoginInfo__login_name'

C:\Users\Administrator\Desktop\SanJinXianFeng-main>

以上是运行报错代码。同样的电脑，重装了下系统。重新部署 出现了新问题

**Comment by FenDou1204** [comment]
这个是main分支的代码吗？我会查看问题，请稍等

**Comment by FenDou1204** [comment]
@sanjinxianfeng  执行 `git pull` 获取最新代码即可
